# python bayesian_finetuning/bin/train.py --config bayesian_finetuning/configs/mini_stsb.yaml

wandb_project_name: 'bayesian_finetuning'

training:
  default_root_dir: '.'
  log_every_n_steps: 10
#  val_check_interval: 50
#  limit_val_batches: 0
  gpus: 1 #1
  accumulate_grad_batches: 1
  max_epochs: 100
  deterministic: True
  data_workers: 4
  train_batch_size: 64
  eval_batch_size: 64
  auto_lr_find: True

prediction:
  model_path: ''

hparams:
  model_name_or_path: prajjwal1/bert-mini
  random_init: True
  task_name: stsb
  eval_metric: pearson
  seed: 1234
  learning_rate: 7.585775750291837e-08
  precision: 32
