# python bayesian_finetuning/bin/train.py --config bayesian_finetuning/configs/small_rte.yaml

wandb_project_name: 'bayesian_finetuning'

training:
  default_root_dir: '.'
  log_every_n_steps: 10
#  val_check_interval: 50
#  limit_val_batches: 0
  gpus: 1 #1
  accumulate_grad_batches: 1
  max_epochs: 100
  deterministic: True
  data_workers: 4
  train_batch_size: 32
  eval_batch_size: 64

prediction:
  model_path: ''

hparams:
  model_name_or_path: prajjwal1/bert-small
  task_name: rte
  eval_metric: accuracy
  seed: 1234
  learning_rate: 2e-5
  precision: 32
